version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: webrtc-ex-back
    command: yarn start
    restart: unless-stopped
    networks:
      - webrtc-ex-network
  frontend:
    build:
      context: ./frontend
    container_name: webrtc-ex-frontend
    command: serve -s dist/app -l 4200
    restart: unless-stopped
    networks:
      - webrtc-ex-network
    depends_on:
      - backend
  nginx:
    image: nginx:stable-alpine
    container_name: webrtc-ex-nginx
    ports:
      - "8082:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - webrtc-ex-network

networks:
  webrtc-ex-network:
    driver: bridge
